#!/usr/bin/env bash

# You must be logged into ghcr.io via `docker login` with your GitHub token first.
# Execute with no arguments to push all images to zk-org ghcr.
# Pass folders as arguments to push selected images only.

if [[ -z $@ ]]; then
    # if no drs passed, build all
    for dir in $(find . -maxdepth 1 -type d -not -name '.*'); do
        docker buildx build -t ghcr.io/zk-org/zk-xcompile:${dir##*/} "${dir}"
    done
else
    # only build images from provided dirs
    for dir in $@; do
        docker buildx build -t ghcr.io/zk-org/zk-xcompile:${dir##*/} "${dir}"
    done
fi
